notice_board/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ToppageView, name='top'),
    path('profile/', views.ProfileView, name='profile'),
    path('thread/<int:pk>/', views.ThreadDetailView, name='thread_detail'),
    path('thread/<int:pk>/post/', views.AddPostView, name='add_post'),
    path('category/<int:pk>/', views.ThreadListView, name='thread_list'),
    path('thread/add/', views.AddThreadView, name='add_thread'),
    path('report/<int:pk>/', views.ReportView, name='report'),

]

university_board/urls.py

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from notice_board import views as board_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', board_views.SignupView, name='signup'),
    path('accounts/login/', views.LoginView.as_view(), name = 'login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page = '/'), name = 'logout'),
    path('', include('notice_board.urls')),
]

notice_board/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

GRADE＿CHOICES = (
    ('1', '学部1年'),
    ('2', '学部2年'),
    ('3', '学部3年'),
    ('4', '学部4年'),
    ('5', '修士1年'),
    ('6', '修士2年'),
)
GENDER_CHOICES = (
    ('1', '女性'),
    ('2', '男性'),
)


class UserProfile(models.Model):
    """
    ユーザープロフィール
    - 各ユーザは一つのプロフィールを持つ

    user:対応するユーザー
    university:大学名
    grade:学年
    gender:性別
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    university = models.ForeignKey('University', on_delete=models.CASCADE)
    mail = models.EmailField(max_length=70)
    grade = models.CharField("学年", max_length=6, choices=GRADE_CHOICES, blank=True)
    gender = models.CharField("性別", max_length=2, choices=GENDER_CHOICES, blank=True)
    is_university = models.BooleanField("大学様用アカウント", default=False)

    def __str__(self):
        return self.user.username


class University(models.Model):
    """
    大学

    name:大学名
    """
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Thread(models.Model):
    """
    スレッド（掲示板）

    university:属している大学
    author:作成者
    title:スレッド名
    created_date:作成日
    category:カテゴリー名
    """
    university = models.ForeignKey('University', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Post(models.Model):
    """
    投稿
    - 各スレッドは0個以上の投稿を持つ

    thread:属しているスレッド
    author:投稿者
    text:投稿内容
    published_date:投稿日
    """
    thread = models.ForeignKey('Thread', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

class Category(models.Model):
    """
    カテゴリー
    
    name:カテゴリー名
    """
    id = models.AutoField(primary_key=True, unique=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Report(models.Model):
    """
    レポート

    university:大学名
    category:カテゴリー
    word:単語
    content:レポート内容
    """
    university = models.ForeignKey('University', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    word = models.CharField(max_length=1000)
    content = models.IntegerField(default=0)

    def __str__(self):
        return self.word

notice_board/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile


class UserCreateForm(UserCreationForm):
    pass


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = (
            "mail", "university", "grade", "gender", "is_university"
        )


notice_board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import UserProfile, Thread, Post, Category, Report
from .forms import ProfileForm, UserCreateForm
from django.contrib.auth.decorators import login_required
# import matplotlib.pyplot as plt
# import numpy as np
# import pandas as pd
# import scipy as sc
# import seaborn as sns
# import MeCab
# import codecs as cd
# from collections import Counter


def SignupView(request):
    """サインアップ"""
    user_form = UserCreateForm(request.POST or None)
    profile_form = ProfileForm(request.POST or None)
    if request.method == "POST" and user_form.is_valid() and profile_form.is_valid():

        # Userモデルの処理
        user = user_form.save(commit=False)
        user.is_active = True
        user.save()

        # Profileモデルの処理
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        return redirect('/')

    context = {
        "user_form": user_form,
        "profile_form": profile_form,
    }
    return render(request, 'registration/signup.html', context)


@login_required
def ProfileView(request):
    """プロフィール"""
    profile = UserProfile.objects.get(user=request.user)
    return render(request, 'notice_board/profilepage.html', {'request': request, 'profile': profile})
    

@login_required
def ToppageView(request):
    """トップページ"""
    profile = UserProfile.objects.get(user=request.user)
    threads = Thread.objects.filter(university=profile.university)
    return render(request, 'notice_board/toppage.html', {'request': request, 'profile':profile, 'threads':threads})


@login_required
def ThreadListView(request, pk):
    """カテゴリーごとの掲示板一覧"""
    if pk == 1:
        cate = '学業・講義'
    elif pk == 2:
        cate='サークル・部活動'
    elif pk == 3:
        cate='アルバイト'
    elif pk == 4:
        cate='就職活動'
    elif pk == 5:
        cate='趣味・遊び'
    elif pk == 6:
        cate = 'その他・雑談'

    profile = UserProfile.objects.get(user=request.user)
    threads = Thread.objects.filter(category=pk, university=profile.university)
    return render(request, 'notice_board/thread_list.html', {'category':cate, 'profile':profile, 'threads':threads})


@login_required
def ThreadDetailView(request, pk):
    """掲示板"""
    thread = get_object_or_404(Thread, pk=pk)
    posts = Post.objects.filter(thread=thread)
    profile = UserProfile.objects.get(user=request.user)
    return render(request, 'notice_board/thread_detail.html', {'thread': thread, 'profile':profile, 'posts':posts})


@login_required
def AddPostView(request, pk):
    """掲示板への投稿"""
    if request.method == "POST": 
        thread = get_object_or_404(Thread, pk=pk)
        posts = Post.objects.filter(thread=thread)
        text = request.POST['post-text']
    
        post = Post()
        post.thread = thread
        post.author = request.user
        post.text = text
        post.save()

    profile = UserProfile.objects.get(user=request.user)
    return render(request, 'notice_board/thread_detail.html', {'thread': thread, 'profile':profile, 'posts':posts})


@login_required
def AddThreadView(request):
    """掲示板の作成"""
    if request.method == "POST": 
        category_id = request.POST['thread-form-category']
        title = request.POST['thread-form-title']
        category = Category.objects.get(id=category_id)
        user = UserProfile.objects.get(user=request.user)

        thread = Thread()
        thread.university = user.university
        thread.author = request.user
        thread.title = title
        thread.category = category
        thread.save()

    thread = Thread.objects.latest('created_date')
    profile = UserProfile.objects.get(user=request.user)
    return render(request, 'notice_board/thread_detail.html', {'thread': thread, 'profile': profile})
    

@login_required
def ReportView(request, pk):
    """レポート"""
    if pk == 1:
        cate = '学業・講義'
    elif pk == 2:
        cate='サークル・部活動'
    elif pk == 3:
        cate='アルバイト'
    elif pk == 4:
        cate='就職活動'
    elif pk == 5:
        cate='趣味・遊び'
    elif pk == 6:
        cate = 'その他・雑談'
    
    reports = Report.objects.filter(category=pk)
    profile = UserProfile.objects.get(user=request.user)
    threads = Thread.objects.filter(category=pk, university=profile.university)


    return render(request, 'notice_board/report.html', {'category':cate, 'profile': profile, 'reports':reports})

notice_board/templates/notice_board/base.html
{% load static %}

<html>

<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/notice_board.css' %}">

</head>

<body>
    <!-- .navbar -->
    {% if profile.is_university %}
    <nav class="navbar" class="fixed">
        <ul class="navbar-list">
            <li class="navbar-item"><a class="navbar-link" href="/">レポート</a></li>
            <li class="navbar-item"><a class="navbar-link" href="{% url 'profile' %}">プロフィール</a></li>
        </ul>
    </nav>
    {% else %}
    <nav class="navbar" class="fixed">
        <ul class="navbar-list">
            <li class="navbar-item"><a class="navbar-link" href="/">掲示板</a></li>
            <li class="navbar-item"><a class="navbar-link" href="{% url 'profile' %}">プロフィール</a></li>
        </ul>
    </nav>
    {% endif %}
    <!-- /.navbar -->

    {% block content %}


    {% endblock %}

</body>

</html>

notice_board/templates/notice_board/profilepage.html
{% extends "notice_board/base.html" %}
{% load static %}

{% block content %}

<div class="profile-section section">
    <div class="section-title profile-title">
        <h3>プロフィール</h3>
    </div>
    {% if profile.is_university %}
    <h3>大学様用アカウント</h3>
    <div class="section-body profile-body">
        <h4>ユーザー名： {{ profile.user }}</h4>
        <h4>メールアドレス： {{ profile.mail }}</h4>
        <h4>大学名： {{ profile.university }}</h4>
    </div>

    {% else %}
    <h3>学生様用アカウント</h3>
    <div class="section-body profile-body">
        <h4>ユーザー名： {{ profile.user }}</h4>
        <h4>メールアドレス： {{ profile.mail }}</h4>
        <h4>大学名： {{ profile.university }}</h4>
        <h4>学年： {{ profile.get_grade_display }}</h4>
        <h4>性別： {{ profile.get_gender_display }}</h4>   
    </div>
    {% endif %}
    <a href="{% url 'logout' %}" class="btn logout-btn">ログアウト</a>
</div>

{% endblock %}

notice_board/templates/notice_board/report.html
{% extends "notice_board/base.html" %}
{% load static %}

{% block content %}

<div class="report-section section">
    <div class="section-title report-title">
        <h3>『{{ category }}』カテゴリーのレポート</h3>
    </div>
    <div class="section-body report-body">
        {% for report in reports %}
        <div class="report-item">
            <h3 class="report-word">単語：　『 {{ report.word }} 』</h3>
            <h3 class="report-content">カウント：　{{ report.content }} 回</h3>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

notice_board/templates/notice_board/thread_detail.html
{% extends "notice_board/base.html" %}
{% load static %}

{% block content %}

<div class="thread-detail-section section">
    <div class="section-title thread-detail-title">
        <p>作成日：{{ thread.created_date }}</p>
        <h2>{{ thread.title }}</h2>
    </div>
    <div class="section-body thread-detail-body">
        <div class="thread-detail-list">
            {% for post in posts %}
                <div class="post">
                    <p>{{ post.published_date }}    <strong>{{ post.author }}</strong></p>
                    <h3>{{ post.text|linebreaksbr }}</h3>
                </div>
            {% endfor %}
        </div>
        
        <form action="{% url 'add_post' pk=thread.pk %}" method="POST" name="post-form">
            {% csrf_token %}
            <div class="post-form" name="post-form">
                <input type="text" class="post-text" name="post-text" required>
            </div>
            <div>
                <button type="submit" class="btn add-post-btn" name='action' value="save">送信</button>
            </div>
        </form>
    </div>

</div>


{% endblock %}

notice_board/templates/notice_board/thread_list.html
{% extends "notice_board/base.html" %}
{% load static %}

{% block content %}

<div class="thread-list-section section">
    <div class="section-title thread-list-title">
        <h3>『{{ category }}』カテゴリーの掲示板一覧</h3>
    </div>
    <div class="section-body thread-list-body">
    {% for thread in threads %}
    <div class="thread-list">
        <p>作成日：{{ thread.created_date }}</p>
        <a href="{% url 'thread_detail' pk=thread.pk %}" class="btn thread-title-btn">{{ thread.title }}</a>
    </div>
    <hr>
    {% endfor %}
    </div>
</div>

{% endblock %}

notice_board/templates/notice_board/toppage.html
{% extends "notice_board/base.html" %}
{% load static %}

{% block content %}

{% if profile.is_university %}
<div class="category-section section">
    <div class="section-title category-title">
        <h3>『{{ profile.university }}』様向け レポート</h3>
    </div>
    <div class="section-body category-body">
        <div class="category-item">
            <a href="{% url 'report' pk=1 %}" class="btn btn-1">学業・講義</a>
        </div>
        <div class="category-item">
            <a href="{% url 'report' pk=2 %}" class="btn btn-2">サークル・部活動</a>
        </div>
        <div class="category-item">
            <a href="{% url 'report' pk=3 %}" class="btn btn-3">アルバイト</a>
        </div>
        <div class="category-item">
            <a href="{% url 'report' pk=4 %}" class="btn btn-4">就職活動</a>
        </div>
        <div class="category-item">
            <a href="{% url 'report' pk=5 %}" class="btn btn-5">趣味・遊び</a>
        </div>
        <div class="category-item">
            <a href="{% url 'report' pk=6 %}" class="btn btn-6">その他・雑談</a>
        </div>
    </div>
</div>

{% else %}
<div class="category-section section">
    <div class="section-title category-title">
        <h3>『{{ profile.university }}』の掲示板</h3>
    </div>
    <div class="section-body category-body">
        <div class="category-item">
            <a href="{% url 'thread_list' pk=1 %}" class="btn btn-1">学業・講義</a>
        </div>
        <div class="category-item">
            <a href="{% url 'thread_list' pk=2 %}" class="btn btn-2">サークル・部活動</a>
        </div>
        <div class="category-item">
            <a href="{% url 'thread_list' pk=3 %}" class="btn btn-3">アルバイト</a>
        </div>
        <div class="category-item">
            <a href="{% url 'thread_list' pk=4 %}" class="btn btn-4">就職活動</a>
        </div>
        <div class="category-item">
            <a href="{% url 'thread_list' pk=5 %}" class="btn btn-5">趣味・遊び</a>
        </div>
        <div class="category-item">
            <a href="{% url 'thread_list' pk=6 %}" class="btn btn-6">その他・雑談</a>
        </div>

        <div class="add-thread">
            <h3>掲示板の作成</h3>
            <form action="{% url 'add_thread' %}" method="POST" name="post-form">
                {% csrf_token %}
                <div class="thread-form" name="thread-form">
                    <label>カテゴリー</label>
                    <select class="thread-form-category" name="thread-form-category">
                        <option value="1">学業・講義</option>
                        <option value="2">サークル・部活動</option>
                        <option value="3">アルバイト</option>
                        <option value="4">就職活動</option>
                        <option value="5">趣味・遊び</option>
                        <option value="6">その他・雑談</option>
                    </select>
                    <br>
                    <label>掲示板タイトル</label>
                    <input type="text" class="thread-form-title" name="thread-form-title" required>
                </div>
                <div>
                    <button type="submit" class="btn add-thread-btn" name='action' value="save">作成する</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}